font:
  normal:
    family: "MesloLGS NF"
    style: Regular
  bold:
    family: "MesloLGS NF"
    style: Bold
  italic:
    family: "MesloLGS NF"
    style: Italic
  bold_italic:
    family: "MesloLGS NF"
    style: Bold Italic

# Colors (Ondark theme)
colors:
  # Default colors
  primary:
    background: "#282C34"
    foreground: "#ABB2BF"

  # Normal colors
  normal:
    black: "#282C34"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#E5C07B"
    blue: "#61AFEF"
    magenta: "#C678DD"
    cyan: "#56B6C2"
    white: "#ABB2BF"

  # Bright colors
  bright:
    black: "#5C6370"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#E5C07B"
    blue: "#61AFEF"
    magenta: "#C678DD"
    cyan: "#56B6C2"
    white: "#FFFFFF"
