#!/bin/bash

charging_noti=1
full_noti=1
low_noti=1

while :
do
  battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`

  ac_power=`acpi -b | grep -c "Charging"`

  battery_full=`acpi -b | grep -c "Full"`

  # Battery Low Notification
  if [[ $battery_level -le 15 && $low_noti -eq 1 ]] 
  then
    dunstify "Battery Low" "Level: $battery_level%" -u critical
    low_noti=0
  elif [ $battery_level -ge 15 ]
  then
    low_noti=1
  fi 

  # Battery Full Notification
  if [[ $battery_full -eq 1 && $full_noti -eq 1 ]]
  then
    dunstify "Battery Full" "Level: $battery_level%" -u normal
    full_noti=0
  elif [ $battery_full -eq 0 ]
  then
    full_noti=1
  fi

  # Battery Charging Notification
  if [[ $ac_power -eq 1 && $charging_noti -eq 1 ]]
  then
    dunstify "Battery Charging" "Level: $battery_level%" -u low
    charging_noti=0
  elif [ $ac_power -eq 0 ]
  then
    charging_noti=1
  fi

  sleep 5s
done
