#!/bin/bash

NOTIFY_ID=2506
SINK_NR=1   # use `pacmd list-sinks` to find out sink_nr

volume=`pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK_NR + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`

mute=`pacmd list-sinks | awk '/muted/ { print $2 }'`

if [ $mute == "yes" ]
then
  dunstify "Volume MUTE" "level: $volume%" -r $NOTIFY_ID -u critical 
else
  dunstify "Volume" "level: $volume%" -r $NOTIFY_ID -u normal 
fi
